import copy
from pathlib import Path
import sys
import unittest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / '.claude/skills/unreal-bridge/scripts'))
import unreal_bridge_graph_codec as g


def fixture(count=3):
    nodes = []
    for i in range(count):
        nodes.append({'guid': f'{i+1:032x}', 'class': 'K2Node_TestUnknown', 'class_path': '/Script/Plugin.TestUnknown',
            'title': '示例', 'x': i * 200, 'y': 0, 'extensions': {'unknown.opaque': '(Field="未来")'},
            'future_node_field': [1, {'v': False}], 'pins': [
                {'id': f'{j+1:032x}', 'persistent_id': '0'*32, 'name': 'input' if j == 0 else 'output',
                 'direction': 'input' if j == 0 else 'output',
                 'type': {'pinCategory': 'int', 'pinSubCategory': '', 'containerType': 'None', 'bIsReference': False, 'future_type': {'a': 1}},
                 'default_value': '42', 'autogenerated_default': '0', 'default_object': 'None',
                 'default_text': 'NSLOCTEXT("Scope","Key","中文")', 'parent': '', 'subpins': [], 'links': [],
                 'orphaned': False, 'default_readonly': False, 'default_ignored': False, 'future_pin_field': {'a': [1, 2]}}
                for j in range(2)]})
    return {'schema': 'unrealbridge.graph_snapshot.v2', 'complete': True, 'graph': 'EventGraph', 'graph_guid': 'f'*32,
            'nodes': nodes, 'wires': [], 'future_graph': {'versions': [3, None]}}


def wire(graph):
    a, b = graph['nodes'][:2]
    a['pins'][1]['links'] = [b['guid'] + ':' + b['pins'][0]['id']]
    b['pins'][0]['links'] = [a['guid'] + ':' + a['pins'][1]['id']]
    graph['wires'] = [{'src': a['guid'], 'src_pin': 'output', 'dst': b['guid'], 'dst_pin': 'input', 'extra': True}]


class GraphCodecTests(unittest.TestCase):
    def test_roundtrip_unknown_types_defaults_unicode(self):
        f = fixture(); wire(f)
        c = g.encode(f)
        self.assertEqual(f, g.decode(c))
        self.assertEqual(c, g.encode(f))
        self.assertEqual(len(c['types']), 1)

    def test_repeated_graph_compression(self):
        f = fixture(100)
        self.assertLess(len(g.encoded(g.encode(f))), len(g.encoded(f)) * .7)

    def test_slice_boundary(self):
        f = fixture(); wire(f)
        c = g.encode(f, node_ids=[f['nodes'][0]['guid']])
        d = g.decode(c)
        self.assertFalse(d['complete']); self.assertEqual(len(d['wires']), 1)
        self.assertEqual(len(d['slice']['boundary_links']), 1)
        with self.assertRaises(g.GraphError): g.dry_run(c, c['source_revision'], [{'op': 'remove_node'}])

    def test_slice_hops_and_layout(self):
        f = fixture(); wire(f)
        c = g.encode(f, node_ids=[f['nodes'][0]['guid']], hops=1, include_layout=False)
        d = g.decode(c)
        self.assertEqual(len(d['nodes']), 2); self.assertNotIn('x', d['nodes'][0])
        self.assertEqual(c['source_revision'], g.revision(f))

    def test_diff_defaults_and_unknown_fields(self):
        a = fixture(); b = copy.deepcopy(a)
        b['nodes'][0]['pins'][0]['default_value'] = '7'
        b['nodes'][0]['extensions']['unknown.opaque'] = 'changed'
        r = g.diff(g.encode(a), g.encode(b))
        self.assertEqual(r['changed_nodes'][0]['fields'], ['extensions', 'pins'])
        self.assertNotEqual(r['before_revision'], r['after_revision'])

    def test_duplicate_and_dangling(self):
        for case in ('node', 'pin', 'link', 'type'):
            f = fixture()
            if case == 'node': f['nodes'][1]['guid'] = f['nodes'][0]['guid']
            if case == 'pin': f['nodes'][0]['pins'][1]['id'] = f['nodes'][0]['pins'][0]['id']
            if case == 'link': f['nodes'][0]['pins'][0]['links'] = ['f'*32 + ':' + 'e'*32]
            if case == 'type': del f['nodes'][0]['pins'][0]['type']
            with self.subTest(case=case), self.assertRaises(g.GraphError): g.encode(f)

    def test_corrupt_dictionary_and_revision(self):
        for corrupt in ('index', 'revision', 'shadow'):
            c = g.encode(fixture())
            if corrupt == 'index': c['nodes'][0][0] = -1
            if corrupt == 'revision': c['revision'] = 'bad'
            if corrupt == 'shadow': c['nodes'][0][-1]['guid'] = 'x'
            with self.subTest(corrupt=corrupt), self.assertRaises(g.GraphError): g.decode(c)

    def test_split_pin_roundtrip(self):
        f = fixture(); a, b = f['nodes'][0]['pins']
        b['parent'] = a['id']; a['subpins'] = [b['id']]
        self.assertEqual(f, g.decode(g.encode(f)))
        b['parent'] = ''
        with self.assertRaises(g.GraphError): g.encode(f)

    def test_typed_default_and_stale_revision(self):
        f = fixture(); c = g.encode(f)
        op = {'op': 'set_pin_default', 'node': f['nodes'][0]['guid'], 'pin': f['nodes'][0]['pins'][0]['id'], 'value': '11'}
        r = g.dry_run(c, c['source_revision'], [op])
        self.assertFalse(r['executed']); self.assertFalse(r['atomic'])
        self.assertEqual(r['operations'][0]['pin'], 'input')
        self.assertEqual(g.decode(c), f)
        with self.assertRaises(g.GraphError): g.dry_run(c, 'old', [op])
        for value in ('NaN', 'abc', str(2**31)):
            with self.subTest(value=value), self.assertRaises(g.GraphError): g.dry_run(c, c['source_revision'], [{**op, 'value': value}])

    def test_connection_and_noop(self):
        f = fixture(); a, b = f['nodes'][:2]; c = g.encode(f)
        op = {'op': 'connect_pins', 'src_node': a['guid'], 'src_pin': a['pins'][1]['id'], 'dst_node': b['guid'], 'dst_pin': b['pins'][0]['id']}
        r = g.dry_run(c, c['source_revision'], [op, op])
        self.assertEqual(len(r['operations']), 1); self.assertEqual(r['no_op_indices'], [1])
        f['nodes'][1]['pins'][0]['type']['pinCategory'] = 'bool'; c = g.encode(f)
        with self.assertRaises(g.GraphError): g.dry_run(c, c['source_revision'], [op])

    def test_ambiguous_names_and_node_deletion_refused(self):
        f = fixture(); f['nodes'][0]['pins'][1]['name'] = 'input'; c = g.encode(f)
        for op in ({'op': 'remove_node'}, {'op': 'set_pin_default', 'node': f['nodes'][0]['guid'], 'pin': f['nodes'][0]['pins'][0]['id'], 'value': '5'}):
            with self.assertRaises(g.GraphError): g.dry_run(c, c['source_revision'], [op])

    def test_incomplete_legacy_refused(self):
        with self.assertRaises(g.GraphError): g.encode({'nodes': [], 'wires': []})


if __name__ == '__main__': unittest.main()
