"""Versioned, bounded Blueprint snapshot codec. Never mutates Editor content."""
from __future__ import annotations

import copy
import hashlib
import json
import math
import re

SCHEMA = 'unrealbridge.graph_compact.v1'
MAX_BYTES = 8 * 1024 * 1024
NODE_STRINGS = ('guid', 'class', 'title', 'class_path')
PIN_STRINGS = ('id', 'persistent_id', 'name', 'direction', 'default_value',
               'autogenerated_default', 'default_object', 'default_text', 'parent')
WIRE_STRINGS = ('src', 'src_pin', 'dst', 'dst_pin')


class GraphError(ValueError):
    pass


def encoded(value):
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(',', ':'), allow_nan=False).encode('utf-8')


def revision(value):
    return hashlib.sha256(encoded(value)).hexdigest()


def _bounded(value):
    try:
        if len(encoded(value)) > MAX_BYTES:
            raise GraphError('Graph exceeds 8 MiB; request a smaller graph, never a silently truncated snapshot')
    except (TypeError, RecursionError, ValueError) as exc:
        raise GraphError(str(exc)) from exc


def validate(graph):
    try:
        return _validate(graph)
    except (AttributeError, TypeError, KeyError, IndexError, RecursionError) as exc:
        raise GraphError('Malformed graph snapshot') from exc


def _validate(graph):
    _bounded(graph)
    if not isinstance(graph, dict) or graph.get('schema') != 'unrealbridge.graph_snapshot.v2':
        raise GraphError('Requires native graph_snapshot.v2 with pin types/defaults')
    if not isinstance(graph.get('complete'), bool):
        raise GraphError('Missing completeness declaration')
    nodes, wires = graph.get('nodes'), graph.get('wires')
    if not isinstance(nodes, list) or not isinstance(wires, list) or len(nodes) > 4096 or len(wires) > 131072:
        raise GraphError('Invalid or oversized node/wire table')
    by_node, pins = {}, {}
    for node in nodes:
        guid = node.get('guid', '')
        if not isinstance(guid, str) or not re.fullmatch('[0-9a-fA-F]{32}', guid) or int(guid, 16) == 0 or guid.casefold() in by_node:
            raise GraphError('Missing, invalid or duplicate node GUID')
        by_node[guid.casefold()] = node
        if not isinstance(node.get('pins'), list):
            raise GraphError('Node lacks pin details')
        for pin in node['pins']:
            pid = pin.get('id', '')
            if not isinstance(pid, str) or not re.fullmatch('[0-9a-fA-F]{32}', pid) or int(pid, 16) == 0:
                raise GraphError('Missing or invalid pin ID')
            key = (guid + ':' + pid).casefold()
            if key in pins:
                raise GraphError('Duplicate pin identity')
            pins[key] = (node, pin)
            if pin.get('direction') not in ('input', 'output') or not isinstance(pin.get('type'), dict) or not pin['type'].get('pinCategory'):
                raise GraphError('Pin direction/type unavailable')
            if not all(isinstance(pin.get(k), str) for k in PIN_STRINGS):
                raise GraphError('Missing pin default/identity data')
            if not all(isinstance(pin.get(k), list) and all(isinstance(v, str) for v in pin[k]) for k in ('links', 'subpins')):
                raise GraphError('Missing pin link/split data')
    if len(pins) > 65536:
        raise GraphError('Too many pins')
    for key, (node, pin) in pins.items():
        if len(set(pin['links'])) != len(pin['links']):
            raise GraphError('Duplicate pin link')
        for linked in pin['links']:
            target = pins.get(linked.casefold())
            if target is None:
                if graph['complete']:
                    raise GraphError('Complete graph contains dangling link')
                continue
            if target[1]['direction'] == pin['direction'] or key not in [v.casefold() for v in target[1]['links']]:
                raise GraphError('Invalid direction or non-reciprocal link')
        for child in pin['subpins']:
            other = pins.get((node['guid'] + ':' + child).casefold())
            if other is None or other[1]['parent'].casefold() != pin['id'].casefold():
                raise GraphError('Invalid split pin relation')
        if pin['parent']:
            parent = pins.get((node['guid'] + ':' + pin['parent']).casefold())
            if parent is None or pin['id'].casefold() not in [v.casefold() for v in parent[1]['subpins']]:
                raise GraphError('Invalid parent pin relation')
    for wire in wires:
        if not all(isinstance(wire.get(k), str) for k in WIRE_STRINGS):
            raise GraphError('Invalid legacy wire row')
        if graph['complete'] and (wire['src'].casefold() not in by_node or wire['dst'].casefold() not in by_node):
            raise GraphError('Dangling legacy wire')
    return by_node, pins


def encode(graph, *, include_layout=True, node_ids=None, hops=0):
    by_node, pins = validate(graph)
    source_revision = revision(graph)
    view = copy.deepcopy(graph)
    if node_ids is not None:
        if not node_ids or not 0 <= hops <= 4:
            raise GraphError('Slice requires node IDs and hops in 0..4')
        selected = {str(v).casefold() for v in node_ids}
        if selected - by_node.keys():
            raise GraphError('Unknown slice node')
        for _ in range(hops):
            selected |= {link.split(':', 1)[0].casefold() for key, (node, pin) in pins.items()
                         if node['guid'].casefold() in selected for link in pin['links']}
        view['nodes'] = [n for n in view['nodes'] if n['guid'].casefold() in selected]
        # Keep boundary edges and pin links. A slice can never authorize an edit.
        view['wires'] = [w for w in view['wires'] if w['src'].casefold() in selected or w['dst'].casefold() in selected]
        view['complete'] = False
        view['slice'] = {'seeds': list(node_ids), 'hops': hops, 'source_node_count': len(graph['nodes']),
                         'boundary_links': sorted({link for n in view['nodes'] for p in n['pins']
                             for link in p['links'] if link.split(':', 1)[0].casefold() not in selected})}
    if not include_layout:
        for node in view['nodes']:
            node.pop('x', None)
            node.pop('y', None)
    strings, string_ids, types, type_ids = [], {}, [], {}

    def intern(value):
        if not isinstance(value, str):
            raise GraphError('String table cell is not a string')
        if value not in string_ids:
            string_ids[value] = len(strings)
            strings.append(value)
        return string_ids[value]

    def fields(row, names):
        return [intern(row[k]) if k in row else None for k in names]

    node_rows = []
    for node in view['nodes']:
        pin_rows = []
        for pin in node['pins']:
            typ = pin['type']
            key = encoded(typ)
            if key not in type_ids:
                type_ids[key] = len(types)
                types.append(typ)
            rest = {k: v for k, v in pin.items() if k not in PIN_STRINGS and k not in ('type', 'links', 'subpins')}
            pin_rows.append(fields(pin, PIN_STRINGS) + [type_ids[key], [intern(v) for v in pin['subpins']],
                [intern(v) for v in pin['links']], rest])
        rest = {k: v for k, v in node.items() if k not in NODE_STRINGS and k != 'pins'}
        node_rows.append(fields(node, NODE_STRINGS) + [pin_rows, rest])
    wire_rows = [fields(w, WIRE_STRINGS) + [{k: v for k, v in w.items() if k not in WIRE_STRINGS}] for w in view['wires']]
    compact = {'schema': SCHEMA, 'source_revision': source_revision, 'revision': revision(view),
        'layout': bool(include_layout), 'complete': view['complete'], 'strings': strings, 'types': types,
        'nodes': node_rows, 'wires': wire_rows, 'meta': {k: v for k, v in view.items() if k not in ('nodes', 'wires')}}
    _bounded(compact)
    return compact


def decode(compact):
    _bounded(compact)
    if not isinstance(compact, dict) or compact.get('schema') != SCHEMA:
        raise GraphError('Unsupported compact schema')
    strings, types = compact.get('strings'), compact.get('types')
    if not isinstance(strings, list) or not all(isinstance(v, str) for v in strings) or not isinstance(types, list):
        raise GraphError('Invalid dictionaries')

    def lookup(table, index):
        if type(index) is not int or not 0 <= index < len(table):
            raise GraphError('Invalid dictionary reference')
        return copy.deepcopy(table[index])

    def unpack(row, names, length):
        if not isinstance(row, list) or len(row) != length or not isinstance(row[-1], dict):
            raise GraphError('Invalid row shape')
        if set(row[-1]) & set(names):
            raise GraphError('Extension shadows table column')
        value = copy.deepcopy(row[-1])
        value.update({k: lookup(strings, row[i]) for i, k in enumerate(names) if row[i] is not None})
        return value

    try:
        graph = copy.deepcopy(compact['meta'])
        if not isinstance(graph, dict) or 'nodes' in graph or 'wires' in graph:
            raise GraphError('Invalid graph metadata')
        graph['nodes'], graph['wires'] = [], []
        for row in compact['nodes']:
            node = unpack(row, NODE_STRINGS, 6)
            if 'pins' in node:
                raise GraphError('Extension shadows pins')
            node['pins'] = []
            for pr in row[4]:
                pin = unpack(pr, PIN_STRINGS, 13)
                if set(pin) & {'type', 'subpins', 'links'}:
                    raise GraphError('Extension shadows pin table')
                pin.update(type=lookup(types, pr[9]), subpins=[lookup(strings, i) for i in pr[10]], links=[lookup(strings, i) for i in pr[11]])
                node['pins'].append(pin)
            graph['nodes'].append(node)
        graph['wires'] = [unpack(row, WIRE_STRINGS, 5) for row in compact['wires']]
        validate(graph)
        if revision(graph) != compact['revision'] or graph['complete'] != compact['complete']:
            raise GraphError('Corrupt revision/completeness')
        if compact['complete'] and compact['layout'] and compact['revision'] != compact['source_revision']:
            raise GraphError('Full graph source revision mismatch')
        return graph
    except (KeyError, TypeError, IndexError, AttributeError) as exc:
        raise GraphError('Malformed compact graph') from exc


def diff(before, after):
    a, b = decode(before), decode(after)
    if a.get('graph_guid') != b.get('graph_guid') or a.get('graph') != b.get('graph'):
        raise GraphError('Cannot diff different graphs')
    an, _ = validate(a)
    bn, _ = validate(b)
    changed = []
    for key in sorted(an.keys() & bn.keys()):
        fields = sorted(k for k in an[key].keys() | bn[key].keys() if an[key].get(k) != bn[key].get(k))
        if fields:
            changed.append({'node': an[key]['guid'], 'fields': fields})
    return {'schema': 'unrealbridge.graph_diff.v1', 'before_revision': before['revision'], 'after_revision': after['revision'],
        'complete': a['complete'] and b['complete'], 'added_nodes': sorted(bn.keys() - an.keys()),
        'removed_nodes': sorted(an.keys() - bn.keys()), 'changed_nodes': changed,
        'wires_changed': a['wires'] != b['wires'], 'metadata_changed': {k: b.get(k) for k in a.keys() | b.keys()
            if k not in ('nodes', 'wires') and a.get(k) != b.get(k)}}


def dry_run(compact, expected_revision, operations):
    graph = decode(compact)
    nodes, pins = validate(graph)
    if not graph['complete'] or not compact['layout'] or expected_revision != compact['source_revision']:
        raise GraphError('Dry-run requires full graph with layout and exact source revision')
    if not isinstance(operations, list) or not 1 <= len(operations) <= 128:
        raise GraphError('Expected 1..128 operations')
    projected = copy.deepcopy(graph)
    _, ppins = validate(projected)
    mapped, noops = [], []

    def select(node_id, pin_id):
        key = (str(node_id) + ':' + str(pin_id)).casefold()
        if key not in ppins:
            raise GraphError('Unknown node/pin ID')
        node, pin = ppins[key]
        if pin.get('orphaned') or pin['parent'] or pin['subpins']:
            raise GraphError('Orphaned/split pin edits require a native schema-specific proposal')
        if sum(p['name'] == pin['name'] for p in node['pins']) != 1:
            raise GraphError('Name-based ApplyGraphOps would resolve an ambiguous pin')
        return node, pin

    for index, op in enumerate(operations):
        if not isinstance(op, dict):
            raise GraphError('Invalid operation')
        kind = op.get('op')
        if kind == 'set_pin_default':
            if set(op) != {'op', 'node', 'pin', 'value'}:
                raise GraphError('Unexpected default operation fields')
            node, pin = select(op['node'], op['pin'])
            typ, value = pin['type'], op['value']
            category = typ.get('pinCategory')
            if pin['direction'] != 'input' or pin['links'] or pin.get('default_readonly') or pin.get('default_ignored'):
                raise GraphError('Pin default cannot be changed safely')
            if not isinstance(value, str) or len(value) > 4096 or typ.get('containerType') not in (None, 'None', 0):
                raise GraphError('Unsupported default value/container')
            if category == 'bool':
                valid = value in ('true', 'false')
            elif category in ('int', 'int64'):
                valid = bool(re.fullmatch(r'-?\d+', value)) and -(2 ** (31 if category == 'int' else 63)) <= int(value) < 2 ** (31 if category == 'int' else 63)
            elif category in ('real', 'float', 'double'):
                try:
                    valid = math.isfinite(float(value))
                except ValueError:
                    valid = False
            else:
                valid = category in ('string', 'name')
            if not valid:
                raise GraphError('Invalid or unsupported typed default; object/text/struct/enum require native schema validation')
            if pin['default_value'] == value:
                noops.append(index)
                continue
            mapped.append({'op': kind, 'graph': graph['graph'], 'node': node['guid'], 'pin': pin['name'], 'value': value})
            pin['default_value'] = value
        elif kind == 'connect_pins':
            if set(op) != {'op', 'src_node', 'src_pin', 'dst_node', 'dst_pin'}:
                raise GraphError('Unexpected connection fields')
            sn, sp = select(op['src_node'], op['src_pin'])
            dn, dp = select(op['dst_node'], op['dst_pin'])
            if sp['direction'] != 'output' or dp['direction'] != 'input' or sp['type'] != dp['type'] or sp['type'].get('pinCategory') in ('wildcard', None):
                raise GraphError('Direction/type mismatch; automatic conversions are not proposed')
            sk, dk = sn['guid'] + ':' + sp['id'], dn['guid'] + ':' + dp['id']
            if dk in sp['links']:
                noops.append(index)
                continue
            if dp['links'] or (sp['type']['pinCategory'] == 'exec' and sp['links']):
                raise GraphError('Would replace an existing connection')
            sp['links'].append(dk)
            dp['links'].append(sk)
            mapped.append({'op': kind, 'graph': graph['graph'], 'src_node': sn['guid'], 'src_pin': sp['name'], 'dst_node': dn['guid'], 'dst_pin': dp['name']})
        else:
            raise GraphError('Dry-run supports existing-pin defaults/connections only; no node deletion or creation')
    return {'success': True, 'schema': 'unrealbridge.graph_proposal.v1', 'dry_run': True, 'expected_revision': expected_revision,
        'operations': mapped, 'no_op_indices': noops, 'executed': False, 'content_saved': False,
        'requires_native_schema_validation': True, 'atomic': False,
        'limitations': 'Preflight proposal only. Re-read revision and obtain an exact asset write scope before native schema validation/application. ApplyGraphOps is not all-or-nothing.'}
