// Auto-generated by tools/gen_version_stubs.py — DO NOT EDIT MANUALLY.
//
// Provides older-engine stub bodies for UFUNCTIONs whose real implementations are
// gated to UE 5.7+ in the corresponding library .cpp. On supported versions this entire
// file compiles to an empty TU. See docs/version-compatibility.md.

#include "UnrealBridgePerfLibrary.h"
#include "Misc/EngineVersionComparison.h"

#if UE_VERSION_OLDER_THAN(5, 7, 0)

FBridgeLumenDiagnostics UUnrealBridgePerfLibrary::GetLumenDiagnostics()
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePerfLibrary::GetLumenDiagnostics requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeLumenDiagnostics{};
}

FBridgeNaniteStats UUnrealBridgePerfLibrary::GetNaniteStats()
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePerfLibrary::GetNaniteStats requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeNaniteStats{};
}

FBridgePerfTraceSummary UUnrealBridgePerfLibrary::ParseTraceToSummary(const FString& UtracePath, int32 TopN, int32 TopNPerThread, int32 TopNCounters)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePerfLibrary::ParseTraceToSummary requires UE 5.7+ — call ignored on this engine version"));
	return FBridgePerfTraceSummary{};
}

FBridgePerfAllocSummary UUnrealBridgePerfLibrary::ParseAllocTraceToSummary(const FString& UtracePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePerfLibrary::ParseAllocTraceToSummary requires UE 5.7+ — call ignored on this engine version"));
	return FBridgePerfAllocSummary{};
}

FBridgePerfNetSummary UUnrealBridgePerfLibrary::ParseNetTraceToSummary(const FString& UtracePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePerfLibrary::ParseNetTraceToSummary requires UE 5.7+ — call ignored on this engine version"));
	return FBridgePerfNetSummary{};
}

FBridgeTextureStreamingState UUnrealBridgePerfLibrary::GetTextureStreamingResidency(int32 TopN)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePerfLibrary::GetTextureStreamingResidency requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeTextureStreamingState{};
}

FBridgeRenderTargetMemory UUnrealBridgePerfLibrary::GetRenderTargetMemory(int32 TopN)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePerfLibrary::GetRenderTargetMemory requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeRenderTargetMemory{};
}

FBridgeGpuPassTimings UUnrealBridgePerfLibrary::GetPerPassGpuTimings()
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePerfLibrary::GetPerPassGpuTimings requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeGpuPassTimings{};
}

FBridgeAllMaterialsAnalysis UUnrealBridgePerfLibrary::AnalyzeAllMaterials(int32 TopN)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePerfLibrary::AnalyzeAllMaterials requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeAllMaterialsAnalysis{};
}

FBridgePerfCookSummary UUnrealBridgePerfLibrary::ParseCookTraceToSummary(const FString& UtracePath, int32 TopN)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePerfLibrary::ParseCookTraceToSummary requires UE 5.7+ — call ignored on this engine version"));
	return FBridgePerfCookSummary{};
}

FBridgePerfSnapshotDelta UUnrealBridgePerfLibrary::ComparePerfSnapshots(const FBridgePerfSnapshot& Before, const FBridgePerfSnapshot& After, float RegressionThreshold)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePerfLibrary::ComparePerfSnapshots requires UE 5.7+ — call ignored on this engine version"));
	return FBridgePerfSnapshotDelta{};
}

FBridgeInsightsLaunchResult UUnrealBridgePerfLibrary::BeginInsightsForTrace(const FString& UtracePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePerfLibrary::BeginInsightsForTrace requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeInsightsLaunchResult{};
}

#endif // UE_VERSION_OLDER_THAN(5, 7, 0)
