// Auto-generated by tools/gen_version_stubs.py — DO NOT EDIT MANUALLY.
//
// Provides older-engine stub bodies for UFUNCTIONs whose real implementations are
// gated to UE 5.7+ in the corresponding library .cpp. On supported versions this entire
// file compiles to an empty TU. See docs/version-compatibility.md.

#include "UnrealBridgeMaterialLibrary.h"
#include "Misc/EngineVersionComparison.h"

#if UE_VERSION_OLDER_THAN(5, 7, 0)

FBridgeMaterialInstanceInfo UUnrealBridgeMaterialLibrary::GetMaterialInstanceParameters(const FString& MaterialPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::GetMaterialInstanceParameters requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeMaterialInstanceInfo{};
}

FBridgeMaterialInfo UUnrealBridgeMaterialLibrary::GetMaterialInfo(const FString& MaterialPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::GetMaterialInfo requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeMaterialInfo{};
}

TArray<FBridgeMaterialFunctionSummary> UUnrealBridgeMaterialLibrary::ListMaterialFunctions(const FString& PathPrefix, int32 MaxResults)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::ListMaterialFunctions requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeMaterialFunctionSummary>{};
}

FBridgeMaterialFunctionInfo UUnrealBridgeMaterialLibrary::GetMaterialFunction(const FString& FunctionPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::GetMaterialFunction requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeMaterialFunctionInfo{};
}

FBridgeMaterialInstanceChain UUnrealBridgeMaterialLibrary::ListMaterialInstanceChain(const FString& MaterialPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::ListMaterialInstanceChain requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeMaterialInstanceChain{};
}

FBridgeMaterialParameterCollectionInfo UUnrealBridgeMaterialLibrary::GetMaterialParameterCollection(const FString& CollectionPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::GetMaterialParameterCollection requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeMaterialParameterCollectionInfo{};
}

FBridgeMaterialGraph UUnrealBridgeMaterialLibrary::GetMaterialGraph(const FString& MaterialPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::GetMaterialGraph requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeMaterialGraph{};
}

FBridgeMaterialStats UUnrealBridgeMaterialLibrary::GetMaterialStats(const FString& MaterialPath, const FString& FeatureLevel, const FString& Quality)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::GetMaterialStats requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeMaterialStats{};
}

TArray<FString> UUnrealBridgeMaterialLibrary::GetMaterialCompileErrors(const FString& MaterialPath, const FString& FeatureLevel, const FString& Quality)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::GetMaterialCompileErrors requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FString>{};
}

FBridgeShaderCompileStatus UUnrealBridgeMaterialLibrary::GetMaterialShaderCompileStatus(const FString& MaterialPath, const FString& FeatureLevel, const FString& Quality)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::GetMaterialShaderCompileStatus requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeShaderCompileStatus{};
}

bool UUnrealBridgeMaterialLibrary::PreviewMaterial(const FString& MaterialPath, const FString& Mesh, const FString& Lighting, int32 Resolution, float CameraYawDeg, float CameraPitchDeg, float CameraDistance, const FString& OutPngPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::PreviewMaterial requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeMaterialLibrary::PreviewMaterialComplexity(const FString& MaterialPath, const FString& Mesh, const FString& Lighting, int32 Resolution, float CameraYawDeg, float CameraPitchDeg, float CameraDistance, const FString& OutPngPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::PreviewMaterialComplexity requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FBridgeCreateAssetResult UUnrealBridgeMaterialLibrary::CreateMaterial(const FString& Path, const FString& Domain, const FString& ShadingModel, const FString& BlendMode, bool bTwoSided, bool bUseMaterialAttributes)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::CreateMaterial requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeCreateAssetResult{};
}

FBridgeCreateAssetResult UUnrealBridgeMaterialLibrary::CreateMaterialInstance(const FString& ParentPath, const FString& InstancePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::CreateMaterialInstance requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeCreateAssetResult{};
}

FBridgeAddExpressionResult UUnrealBridgeMaterialLibrary::AddMaterialExpression(const FString& MaterialPath, const FString& ExpressionClass, int32 X, int32 Y)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::AddMaterialExpression requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeAddExpressionResult{};
}

bool UUnrealBridgeMaterialLibrary::ConnectMaterialExpressions(const FString& MaterialPath, FGuid SrcGuid, const FString& SrcOutputName, FGuid DstGuid, const FString& DstInputName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::ConnectMaterialExpressions requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeMaterialLibrary::DisconnectMaterialInput(const FString& MaterialPath, FGuid DstGuid, const FString& DstInputName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::DisconnectMaterialInput requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeMaterialLibrary::ConnectMaterialOutput(const FString& MaterialPath, FGuid SrcGuid, const FString& SrcOutputName, const FString& PropertyName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::ConnectMaterialOutput requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeMaterialLibrary::DisconnectMaterialOutput(const FString& MaterialPath, const FString& PropertyName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::DisconnectMaterialOutput requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeMaterialLibrary::DeleteMaterialExpression(const FString& MaterialPath, FGuid Guid)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::DeleteMaterialExpression requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeMaterialLibrary::CompileMaterial(const FString& MaterialPath, bool bSaveAfter)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::CompileMaterial requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeMaterialLibrary::SetMaterialExpressionProperty(const FString& MaterialPath, FGuid Guid, const FString& PropertyName, const FString& Value)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::SetMaterialExpressionProperty requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

int32 UUnrealBridgeMaterialLibrary::SetMaterialExpressionProperties(const FString& MaterialPath, FGuid Guid, const TArray<FBridgeExpressionPropSet>& Properties)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::SetMaterialExpressionProperties requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

FGuid UUnrealBridgeMaterialLibrary::AddMaterialComment(const FString& MaterialPath, int32 X, int32 Y, int32 Width, int32 Height, const FString& Text, FLinearColor Color)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::AddMaterialComment requires UE 5.7+ — call ignored on this engine version"));
	return FGuid{};
}

FGuid UUnrealBridgeMaterialLibrary::AddMaterialReroute(const FString& MaterialPath, int32 X, int32 Y)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::AddMaterialReroute requires UE 5.7+ — call ignored on this engine version"));
	return FGuid{};
}

FBridgeCreateAssetResult UUnrealBridgeMaterialLibrary::CreateMaterialFunction(const FString& Path, const FString& Description, bool bExposeToLibrary, const FString& LibraryCategory)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::CreateMaterialFunction requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeCreateAssetResult{};
}

FBridgeMaterialGraphOpResult UUnrealBridgeMaterialLibrary::ApplyMaterialGraphOps(const FString& MaterialPath, const TArray<FBridgeMaterialGraphOp>& Ops, bool bCompile)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::ApplyMaterialGraphOps requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeMaterialGraphOpResult{};
}

int32 UUnrealBridgeMaterialLibrary::AutoLayoutMaterialGraph(const FString& MaterialPath, int32 ColumnSpacing, int32 RowSpacing)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::AutoLayoutMaterialGraph requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

FString UUnrealBridgeMaterialLibrary::SnapshotMaterialGraphJson(const FString& MaterialPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::SnapshotMaterialGraphJson requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

FString UUnrealBridgeMaterialLibrary::DiffMaterialGraphSnapshots(const FString& BeforeJson, const FString& AfterJson)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::DiffMaterialGraphSnapshots requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

FBridgeAddExpressionResult UUnrealBridgeMaterialLibrary::AddCustomExpression(const FString& MaterialPath, int32 X, int32 Y, const TArray<FString>& InputNames, const FString& OutputType, const FString& Code, const TArray<FString>& IncludePaths, const FString& Description)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::AddCustomExpression requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeAddExpressionResult{};
}

TArray<FBridgeShaderSnippet> UUnrealBridgeMaterialLibrary::ListSharedSnippets()
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::ListSharedSnippets requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeShaderSnippet>{};
}

FBridgeShaderSnippet UUnrealBridgeMaterialLibrary::GetSharedSnippet(const FString& Name)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::GetSharedSnippet requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeShaderSnippet{};
}

FBridgeMIParamResult UUnrealBridgeMaterialLibrary::SetMIParams(const FString& MaterialInstancePath, const TArray<FBridgeMIParamSet>& Params)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::SetMIParams requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeMIParamResult{};
}

bool UUnrealBridgeMaterialLibrary::SetMIAndPreview(const FString& MaterialInstancePath, const TArray<FBridgeMIParamSet>& Params, const FString& Mesh, const FString& Lighting, int32 Resolution, float CameraYawDeg, float CameraPitchDeg, float CameraDistance, const FString& OutPngPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::SetMIAndPreview requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FString> UUnrealBridgeMaterialLibrary::SweepMIParams(const FString& MaterialInstancePath, const FString& ParamName, const TArray<FString>& Values, const FString& Mesh, const FString& Lighting, int32 Resolution, float CameraYawDeg, float CameraPitchDeg, float CameraDistance, int32 GridCols, const FString& OutGridPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::SweepMIParams requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FString>{};
}

FBridgeMIParamResult UUnrealBridgeMaterialLibrary::SetMaterialParameterCollection(const FString& CollectionPath, const TArray<FBridgeMIParamSet>& Params)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::SetMaterialParameterCollection requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeMIParamResult{};
}

FString UUnrealBridgeMaterialLibrary::DiffMIParams(const FString& PathA, const FString& PathB)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::DiffMIParams requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

FBridgeCreateAssetResult UUnrealBridgeMaterialLibrary::CreatePostProcessMaterial(const FString& Path, const FString& BlendableLocation, bool bOutputAlpha)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::CreatePostProcessMaterial requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeCreateAssetResult{};
}

TArray<FBridgePostProcessVolumeInfo> UUnrealBridgeMaterialLibrary::GetPostProcessState()
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::GetPostProcessState requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgePostProcessVolumeInfo>{};
}

bool UUnrealBridgeMaterialLibrary::ApplyPostProcessMaterial(const FString& VolumeActor, const FString& MaterialPath, float Weight)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::ApplyPostProcessMaterial requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeMaterialLibrary::RemovePostProcessMaterial(const FString& VolumeActor, const FString& MaterialPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::RemovePostProcessMaterial requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FBridgeMaterialAnalysis UUnrealBridgeMaterialLibrary::AnalyzeMaterial(const FString& MaterialPath, int32 InstructionBudget, int32 SamplerBudget)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::AnalyzeMaterial requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeMaterialAnalysis{};
}

FBridgeMaterialAutoFixResult UUnrealBridgeMaterialLibrary::AutoFixMaterial(const FString& MaterialPath, const TArray<FString>& Fixes, bool bSaveAfter)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::AutoFixMaterial requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeMaterialAutoFixResult{};
}

FBridgeMaterialGraphOpResult UUnrealBridgeMaterialLibrary::SetMaterialAttributeLayers(const FString& MaterialPath, FGuid ExpressionGuid, const TArray<UMaterialFunctionInterface*>& Layers, const TArray<UMaterialFunctionInterface*>& Blends, const TArray<FString>& LayerNames)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeMaterialLibrary::SetMaterialAttributeLayers requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeMaterialGraphOpResult{};
}

#endif // UE_VERSION_OLDER_THAN(5, 7, 0)
