// Auto-generated by tools/gen_version_stubs.py — DO NOT EDIT MANUALLY.
//
// Provides older-engine stub bodies for UFUNCTIONs whose real implementations are
// gated to UE 5.6+ in the corresponding library .cpp. On supported versions this entire
// file compiles to an empty TU. See docs/version-compatibility.md.

#include "UnrealBridgePoseSearchLibrary.h"
#include "Misc/EngineVersionComparison.h"

#if UE_VERSION_OLDER_THAN(5, 6, 0)

FBridgePSSInfo UUnrealBridgePoseSearchLibrary::GetSchemaInfo(const FString& SchemaPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePoseSearchLibrary::GetSchemaInfo requires UE 5.6+ — call ignored on this engine version"));
	return FBridgePSSInfo{};
}

TArray<FBridgePSSChannel> UUnrealBridgePoseSearchLibrary::ListSchemaChannels(const FString& SchemaPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePoseSearchLibrary::ListSchemaChannels requires UE 5.6+ — call ignored on this engine version"));
	return TArray<FBridgePSSChannel>{};
}

FBridgePSDInfo UUnrealBridgePoseSearchLibrary::GetDatabaseInfo(const FString& DatabasePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePoseSearchLibrary::GetDatabaseInfo requires UE 5.6+ — call ignored on this engine version"));
	return FBridgePSDInfo{};
}

TArray<FBridgePSDAnimEntry> UUnrealBridgePoseSearchLibrary::ListDatabaseAnimations(const FString& DatabasePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePoseSearchLibrary::ListDatabaseAnimations requires UE 5.6+ — call ignored on this engine version"));
	return TArray<FBridgePSDAnimEntry>{};
}

TArray<FString> UUnrealBridgePoseSearchLibrary::FindDatabasesUsingAnimation(const FString& AnimationAssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePoseSearchLibrary::FindDatabasesUsingAnimation requires UE 5.6+ — call ignored on this engine version"));
	return TArray<FString>{};
}

FBridgePSDAddResult UUnrealBridgePoseSearchLibrary::AddAnimationToDatabase(const FString& DatabasePath, const FString& AnimationAssetPath, float SamplingRangeMin, float SamplingRangeMax, const FString& MirrorOption, bool bEnabled)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePoseSearchLibrary::AddAnimationToDatabase requires UE 5.6+ — call ignored on this engine version"));
	return FBridgePSDAddResult{};
}

FBridgePSDAddResult UUnrealBridgePoseSearchLibrary::AddBlendSpaceToDatabase(const FString& DatabasePath, const FString& BlendSpacePath, int32 HSamples, int32 VSamples, bool bUseGridForSampling, bool bUseSingleSample, float BlendParamX, float BlendParamY, float SamplingRangeMin, float SamplingRangeMax, const FString& MirrorOption, bool bEnabled)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePoseSearchLibrary::AddBlendSpaceToDatabase requires UE 5.6+ — call ignored on this engine version"));
	return FBridgePSDAddResult{};
}

bool UUnrealBridgePoseSearchLibrary::RemoveDatabaseAnimationAt(const FString& DatabasePath, int32 Index)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePoseSearchLibrary::RemoveDatabaseAnimationAt requires UE 5.6+ — call ignored on this engine version"));
	return bool{};
}

int32 UUnrealBridgePoseSearchLibrary::RemoveDatabaseAnimationByAsset(const FString& DatabasePath, const FString& AnimationAssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePoseSearchLibrary::RemoveDatabaseAnimationByAsset requires UE 5.6+ — call ignored on this engine version"));
	return int32{};
}

int32 UUnrealBridgePoseSearchLibrary::ClearDatabaseAnimations(const FString& DatabasePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePoseSearchLibrary::ClearDatabaseAnimations requires UE 5.6+ — call ignored on this engine version"));
	return int32{};
}

bool UUnrealBridgePoseSearchLibrary::SetDatabaseAnimationEnabled(const FString& DatabasePath, int32 Index, bool bEnabled)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePoseSearchLibrary::SetDatabaseAnimationEnabled requires UE 5.6+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgePoseSearchLibrary::SetDatabaseAnimationSamplingRange(const FString& DatabasePath, int32 Index, float SamplingRangeMin, float SamplingRangeMax)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePoseSearchLibrary::SetDatabaseAnimationSamplingRange requires UE 5.6+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgePoseSearchLibrary::SetDatabaseAnimationMirrorOption(const FString& DatabasePath, int32 Index, const FString& MirrorOption)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePoseSearchLibrary::SetDatabaseAnimationMirrorOption requires UE 5.6+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgePoseSearchLibrary::SetDatabaseBlendSpaceSampling(const FString& DatabasePath, int32 Index, int32 HSamples, int32 VSamples, bool bUseGridForSampling, bool bUseSingleSample, float BlendParamX, float BlendParamY)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePoseSearchLibrary::SetDatabaseBlendSpaceSampling requires UE 5.6+ — call ignored on this engine version"));
	return bool{};
}

FString UUnrealBridgePoseSearchLibrary::RequestAsyncBuildIndex(const FString& DatabasePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePoseSearchLibrary::RequestAsyncBuildIndex requires UE 5.6+ — call ignored on this engine version"));
	return FString{};
}

bool UUnrealBridgePoseSearchLibrary::IsIndexReady(const FString& DatabasePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePoseSearchLibrary::IsIndexReady requires UE 5.6+ — call ignored on this engine version"));
	return bool{};
}

FString UUnrealBridgePoseSearchLibrary::GetIndexStatus(const FString& DatabasePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePoseSearchLibrary::GetIndexStatus requires UE 5.6+ — call ignored on this engine version"));
	return FString{};
}

FBridgePoseSearchIndexPollResult UUnrealBridgePoseSearchLibrary::WaitPoseSearchIndex(const FString& DatabasePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePoseSearchLibrary::WaitPoseSearchIndex requires UE 5.6+ — call ignored on this engine version"));
	return FBridgePoseSearchIndexPollResult{};
}

bool UUnrealBridgePoseSearchLibrary::InvalidateIndex(const FString& DatabasePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePoseSearchLibrary::InvalidateIndex requires UE 5.6+ — call ignored on this engine version"));
	return bool{};
}

#endif // UE_VERSION_OLDER_THAN(5, 6, 0)
