// Auto-generated by tools/gen_version_stubs.py — DO NOT EDIT MANUALLY.
//
// Provides older-engine stub bodies for UFUNCTIONs whose real implementations are
// gated to UE 5.7+ in the corresponding library .cpp. On supported versions this entire
// file compiles to an empty TU. See docs/version-compatibility.md.

#include "UnrealBridgeDataTableLibrary.h"
#include "Misc/EngineVersionComparison.h"

#if UE_VERSION_OLDER_THAN(5, 7, 0)

int32 UUnrealBridgeDataTableLibrary::CopyDataTableRows(const FString& SourceDataTablePath, const FString& DestDataTablePath, const TArray<FString>& RowNames, bool bOverwrite)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeDataTableLibrary::CopyDataTableRows requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

#endif // UE_VERSION_OLDER_THAN(5, 7, 0)
