// Auto-generated by tools/gen_version_stubs.py — DO NOT EDIT MANUALLY.
//
// Provides older-engine stub bodies for UFUNCTIONs whose real implementations are
// gated to UE 5.7+ in the corresponding library .cpp. On supported versions this entire
// file compiles to an empty TU. See docs/version-compatibility.md.

#include "UnrealBridgeBlueprintLibrary.h"
#include "Misc/EngineVersionComparison.h"

#if UE_VERSION_OLDER_THAN(5, 7, 0)

FString UUnrealBridgeBlueprintLibrary::AddAsyncActionNode(const FString& BlueprintPath, const FString& GraphName, const FString& FactoryClassPath, const FString& FactoryFunctionName, int32 NodePosX, int32 NodePosY)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeBlueprintLibrary::AddAsyncActionNode requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

#endif // UE_VERSION_OLDER_THAN(5, 7, 0)
