// Auto-generated by tools/gen_version_stubs.py — DO NOT EDIT MANUALLY.
//
// Provides older-engine stub bodies for UFUNCTIONs whose real implementations are
// gated to UE 5.6+ in the corresponding library .cpp. On supported versions this entire
// file compiles to an empty TU. See docs/version-compatibility.md.

#include "UnrealBridgePCGLibrary.h"
#include "Misc/EngineVersionComparison.h"

#if UE_VERSION_OLDER_THAN(5, 6, 0)

TArray<FString> UUnrealBridgePCGLibrary::ListPCGGraphAssets(const FString& Filter, int32 Max)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePCGLibrary::ListPCGGraphAssets requires UE 5.6+ — call ignored on this engine version"));
	return TArray<FString>{};
}

TArray<FBridgePCGComponentEntry> UUnrealBridgePCGLibrary::ListPCGComponentsInLevel(const FString& LevelFilter, int32 Max)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePCGLibrary::ListPCGComponentsInLevel requires UE 5.6+ — call ignored on this engine version"));
	return TArray<FBridgePCGComponentEntry>{};
}

FBridgePCGComponentState UUnrealBridgePCGLibrary::GetPCGComponentState(const FString& ActorLabel, const FString& ComponentName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePCGLibrary::GetPCGComponentState requires UE 5.6+ — call ignored on this engine version"));
	return FBridgePCGComponentState{};
}

TArray<FBridgePCGOverrideEntry> UUnrealBridgePCGLibrary::GetPCGComponentOverrides(const FString& ActorLabel, const FString& ComponentName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePCGLibrary::GetPCGComponentOverrides requires UE 5.6+ — call ignored on this engine version"));
	return TArray<FBridgePCGOverrideEntry>{};
}

bool UUnrealBridgePCGLibrary::SetPCGComponentOverride(const FString& ActorLabel, const FString& ComponentName, const FString& Name, const FString& ExportedValue)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePCGLibrary::SetPCGComponentOverride requires UE 5.6+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgePCGLibrary::TriggerPCGGenerate(const FString& ActorLabel, const FString& ComponentName, bool bForce)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePCGLibrary::TriggerPCGGenerate requires UE 5.6+ — call ignored on this engine version"));
	return bool{};
}

FBridgePCGWaitResult UUnrealBridgePCGLibrary::WaitForPCGGenerate(const FString& ActorLabel, const FString& ComponentName, float TimeoutSec)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePCGLibrary::WaitForPCGGenerate requires UE 5.6+ — call ignored on this engine version"));
	return FBridgePCGWaitResult{};
}

FBridgePCGGenerationPollResult UUnrealBridgePCGLibrary::WaitPCGGeneration(const FString& ActorLabel, const FString& ComponentName)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePCGLibrary::WaitPCGGeneration requires UE 5.6+ — call ignored on this engine version"));
	return FBridgePCGGenerationPollResult{};
}

bool UUnrealBridgePCGLibrary::CleanupPCGComponent(const FString& ActorLabel, const FString& ComponentName, bool bRemoveComponents)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePCGLibrary::CleanupPCGComponent requires UE 5.6+ — call ignored on this engine version"));
	return bool{};
}

FBridgePCGGraphInfo UUnrealBridgePCGLibrary::GetPCGGraphStructure(const FString& GraphPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePCGLibrary::GetPCGGraphStructure requires UE 5.6+ — call ignored on this engine version"));
	return FBridgePCGGraphInfo{};
}

FBridgePCGGraphValidationResult UUnrealBridgePCGLibrary::ValidatePCGGraph(const FString& GraphPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePCGLibrary::ValidatePCGGraph requires UE 5.6+ — call ignored on this engine version"));
	return FBridgePCGGraphValidationResult{};
}

FBridgePCGGraphEditResult UUnrealBridgePCGLibrary::AddPCGGraphNode(const FString& GraphPath, const FString& SettingsClassPath, const FString& NodeTitle, int32 PositionX, int32 PositionY, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePCGLibrary::AddPCGGraphNode requires UE 5.6+ — call ignored on this engine version"));
	return FBridgePCGGraphEditResult{};
}

FBridgePCGGraphEditResult UUnrealBridgePCGLibrary::ConnectPCGGraphNodes(const FString& GraphPath, const FString& FromNodeId, const FString& FromPin, const FString& ToNodeId, const FString& ToPin, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePCGLibrary::ConnectPCGGraphNodes requires UE 5.6+ — call ignored on this engine version"));
	return FBridgePCGGraphEditResult{};
}

FBridgePCGGraphEditResult UUnrealBridgePCGLibrary::SetPCGNodeSettingsProperty(const FString& GraphPath, const FString& NodeId, const FString& PropertyName, const FString& ValueExportText, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePCGLibrary::SetPCGNodeSettingsProperty requires UE 5.6+ — call ignored on this engine version"));
	return FBridgePCGGraphEditResult{};
}

FBridgePCGGraphEditResult UUnrealBridgePCGLibrary::SetPCGNodeEnabled(const FString& GraphPath, const FString& NodeId, bool bEnabled, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgePCGLibrary::SetPCGNodeEnabled requires UE 5.6+ — call ignored on this engine version"));
	return FBridgePCGGraphEditResult{};
}

#endif // UE_VERSION_OLDER_THAN(5, 6, 0)
