// Auto-generated by tools/gen_version_stubs.py — DO NOT EDIT MANUALLY.
//
// Provides older-engine stub bodies for UFUNCTIONs whose real implementations are
// gated to UE 5.7+ in the corresponding library .cpp. On supported versions this entire
// file compiles to an empty TU. See docs/version-compatibility.md.

#include "UnrealBridgeNavigationLibrary.h"
#include "Misc/EngineVersionComparison.h"

#if UE_VERSION_OLDER_THAN(5, 7, 0)

bool UUnrealBridgeNavigationLibrary::ExportNavMeshToObj(const FString& OutFilePath, FString& OutSummary)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeNavigationLibrary::ExportNavMeshToObj requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

#endif // UE_VERSION_OLDER_THAN(5, 7, 0)
