// Auto-generated by tools/gen_version_stubs.py — DO NOT EDIT MANUALLY.
//
// Provides older-engine stub bodies for UFUNCTIONs whose real implementations are
// gated to UE 5.7+ in the corresponding library .cpp. On supported versions this entire
// file compiles to an empty TU. See docs/version-compatibility.md.

#include "UnrealBridgeGeometryLibrary.h"
#include "Misc/EngineVersionComparison.h"

#if UE_VERSION_OLDER_THAN(5, 7, 0)

int32 UUnrealBridgeGeometryLibrary::CreateDynamicMesh()
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeGeometryLibrary::CreateDynamicMesh requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

bool UUnrealBridgeGeometryLibrary::ReleaseDynamicMesh(int32 Handle)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeGeometryLibrary::ReleaseDynamicMesh requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<int32> UUnrealBridgeGeometryLibrary::ListDynamicMeshHandles()
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeGeometryLibrary::ListDynamicMeshHandles requires UE 5.7+ — call ignored on this engine version"));
	return TArray<int32>{};
}

bool UUnrealBridgeGeometryLibrary::LoadMeshFromStaticMesh(int32 Handle, const FString& AssetPath, int32 Lod)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeGeometryLibrary::LoadMeshFromStaticMesh requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeGeometryLibrary::LoadMeshFromComponent(const FString& ActorLabel, const FString& ComponentName, int32 Handle)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeGeometryLibrary::LoadMeshFromComponent requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FString UUnrealBridgeGeometryLibrary::SaveMeshToNewStaticMesh(int32 Handle, const FString& NewAssetPath, const TArray<UMaterialInterface*>& MaterialList)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeGeometryLibrary::SaveMeshToNewStaticMesh requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UUnrealBridgeGeometryLibrary::SaveMeshToExistingStaticMesh(int32 Handle, const FString& ExistingAssetPath, bool bReplaceMaterials)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeGeometryLibrary::SaveMeshToExistingStaticMesh requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FBridgeMeshInfo UUnrealBridgeGeometryLibrary::GetMeshInfo(int32 Handle)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeGeometryLibrary::GetMeshInfo requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeMeshInfo{};
}

bool UUnrealBridgeGeometryLibrary::MeshBoolean(int32 HandleA, int32 HandleB, const FString& Op)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeGeometryLibrary::MeshBoolean requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeGeometryLibrary::MeshSmooth(int32 Handle, int32 Iterations, float Strength)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeGeometryLibrary::MeshSmooth requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeGeometryLibrary::MeshDecimate(int32 Handle, int32 TargetTris)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeGeometryLibrary::MeshDecimate requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeGeometryLibrary::RecomputeNormalsAndTangents(int32 Handle, float AngleThresholdDeg)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeGeometryLibrary::RecomputeNormalsAndTangents requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeGeometryLibrary::AppendBox(int32 Handle, FVector Origin, FVector Size)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeGeometryLibrary::AppendBox requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeGeometryLibrary::AppendSphere(int32 Handle, FVector Origin, float Radius, int32 ResolutionUV)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeGeometryLibrary::AppendSphere requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeGeometryLibrary::AppendCylinder(int32 Handle, FVector Origin, float Radius, float Height, int32 RadialSegments)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeGeometryLibrary::AppendCylinder requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeGeometryLibrary::AppendCone(int32 Handle, FVector Origin, float BaseRadius, float Height, int32 RadialSegments)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeGeometryLibrary::AppendCone requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeGeometryLibrary::MeshTransform(int32 Handle, FTransform Transform)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeGeometryLibrary::MeshTransform requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeGeometryLibrary::MeshUniformRemesh(int32 Handle, int32 TargetTriCount)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeGeometryLibrary::MeshUniformRemesh requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeGeometryLibrary::MeshDisplaceFromTexture(int32 Handle, const FString& TexturePath, float Magnitude, int32 UVChannel)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeGeometryLibrary::MeshDisplaceFromTexture requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeGeometryLibrary::MeshVoxelMerge(const TArray<int32>& Handles, float CellSizeCm)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeGeometryLibrary::MeshVoxelMerge requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeGeometryLibrary::MeshUVUnwrap(int32 Handle, const FString& Method)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeGeometryLibrary::MeshUVUnwrap requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

int32 UUnrealBridgeGeometryLibrary::SelectByNormalDirection(int32 Handle, FVector Normal, float MaxAngleDeg)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeGeometryLibrary::SelectByNormalDirection requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

bool UUnrealBridgeGeometryLibrary::ReleaseSelection(int32 SelectionId)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeGeometryLibrary::ReleaseSelection requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<int32> UUnrealBridgeGeometryLibrary::ListSelections()
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeGeometryLibrary::ListSelections requires UE 5.7+ — call ignored on this engine version"));
	return TArray<int32>{};
}

bool UUnrealBridgeGeometryLibrary::ExtrudeSelection(int32 Handle, int32 SelectionId, float Distance)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeGeometryLibrary::ExtrudeSelection requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeGeometryLibrary::SweepAlongSpline(int32 Handle, const TArray<FVector2D>& ProfileXY, const FString& ActorLabel, const FString& ComponentName, int32 NumPathSamples)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeGeometryLibrary::SweepAlongSpline requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FString UUnrealBridgeGeometryLibrary::BakeNormalsToTexture(int32 Handle, const FString& NewTexturePath, int32 Resolution)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeGeometryLibrary::BakeNormalsToTexture requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UUnrealBridgeGeometryLibrary::BakeOcclusionToVertexColor(int32 Handle, int32 OcclusionRays)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeGeometryLibrary::BakeOcclusionToVertexColor requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

#endif // UE_VERSION_OLDER_THAN(5, 7, 0)
