// Auto-generated by tools/gen_version_stubs.py — DO NOT EDIT MANUALLY.
//
// Provides older-engine stub bodies for UFUNCTIONs whose real implementations are
// gated to UE 5.7+ in the corresponding library .cpp. On supported versions this entire
// file compiles to an empty TU. See docs/version-compatibility.md.

#include "UnrealBridgeChooserLibrary.h"
#include "Misc/EngineVersionComparison.h"

#if UE_VERSION_OLDER_THAN(5, 7, 0)

FBridgeCHTInfo UUnrealBridgeChooserLibrary::GetChooserInfo(const FString& ChooserTablePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeChooserLibrary::GetChooserInfo requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeCHTInfo{};
}

TArray<FBridgeCHTColumn> UUnrealBridgeChooserLibrary::ListChooserColumns(const FString& ChooserTablePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeChooserLibrary::ListChooserColumns requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeCHTColumn>{};
}

TArray<FBridgeCHTRow> UUnrealBridgeChooserLibrary::ListChooserRows(const FString& ChooserTablePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeChooserLibrary::ListChooserRows requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeCHTRow>{};
}

FBridgeCHTRowResult UUnrealBridgeChooserLibrary::GetChooserRowResult(const FString& ChooserTablePath, int32 RowIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeChooserLibrary::GetChooserRowResult requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeCHTRowResult{};
}

FString UUnrealBridgeChooserLibrary::GetChooserCellRaw(const FString& ChooserTablePath, int32 ColumnIndex, int32 RowIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeChooserLibrary::GetChooserCellRaw requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

int32 UUnrealBridgeChooserLibrary::AddChooserRow(const FString& ChooserTablePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeChooserLibrary::AddChooserRow requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

int32 UUnrealBridgeChooserLibrary::InsertChooserRow(const FString& ChooserTablePath, int32 BeforeRow)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeChooserLibrary::InsertChooserRow requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

bool UUnrealBridgeChooserLibrary::RemoveChooserRow(const FString& ChooserTablePath, int32 RowIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeChooserLibrary::RemoveChooserRow requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeChooserLibrary::SetChooserRowDisabled(const FString& ChooserTablePath, int32 RowIndex, bool bDisabled)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeChooserLibrary::SetChooserRowDisabled requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeChooserLibrary::SetChooserRowResultAsset(const FString& ChooserTablePath, int32 RowIndex, const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeChooserLibrary::SetChooserRowResultAsset requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeChooserLibrary::SetChooserRowResultClass(const FString& ChooserTablePath, int32 RowIndex, const FString& ClassPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeChooserLibrary::SetChooserRowResultClass requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeChooserLibrary::SetChooserRowResultEvaluateChooser(const FString& ChooserTablePath, int32 RowIndex, const FString& SubChooserPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeChooserLibrary::SetChooserRowResultEvaluateChooser requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeChooserLibrary::ClearChooserRowResult(const FString& ChooserTablePath, int32 RowIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeChooserLibrary::ClearChooserRowResult requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeChooserLibrary::SetChooserFallbackAsset(const FString& ChooserTablePath, const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeChooserLibrary::SetChooserFallbackAsset requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeChooserLibrary::ClearChooserFallback(const FString& ChooserTablePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeChooserLibrary::ClearChooserFallback requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeChooserLibrary::SetChooserContextObjectClass(const FString& ChooserTablePath, const FString& ContextClassPath, const FString& Direction)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeChooserLibrary::SetChooserContextObjectClass requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeChooserLibrary::CompileChooser(const FString& ChooserTablePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeChooserLibrary::CompileChooser requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FString UUnrealBridgeChooserLibrary::GetLastChooserError()
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeChooserLibrary::GetLastChooserError requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

int32 UUnrealBridgeChooserLibrary::AddChooserColumnByStructPath(const FString& ChooserTablePath, const FString& ColumnStructPath, const FString& BindingPropertyChain, int32 ContextIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeChooserLibrary::AddChooserColumnByStructPath requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

int32 UUnrealBridgeChooserLibrary::AddChooserColumnFloatRange(const FString& ChooserTablePath, const FString& BindingPropertyChain, int32 ContextIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeChooserLibrary::AddChooserColumnFloatRange requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

int32 UUnrealBridgeChooserLibrary::AddChooserColumnEnum(const FString& ChooserTablePath, const FString& BindingPropertyChain, const FString& EnumPath, int32 ContextIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeChooserLibrary::AddChooserColumnEnum requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

int32 UUnrealBridgeChooserLibrary::AddChooserColumnBool(const FString& ChooserTablePath, const FString& BindingPropertyChain, int32 ContextIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeChooserLibrary::AddChooserColumnBool requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

int32 UUnrealBridgeChooserLibrary::AddChooserColumnObject(const FString& ChooserTablePath, const FString& BindingPropertyChain, int32 ContextIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeChooserLibrary::AddChooserColumnObject requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

int32 UUnrealBridgeChooserLibrary::AddChooserColumnGameplayTag(const FString& ChooserTablePath, const FString& BindingPropertyChain, int32 ContextIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeChooserLibrary::AddChooserColumnGameplayTag requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

int32 UUnrealBridgeChooserLibrary::AddChooserColumnRandomize(const FString& ChooserTablePath, const FString& BindingPropertyChain, int32 ContextIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeChooserLibrary::AddChooserColumnRandomize requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

int32 UUnrealBridgeChooserLibrary::AddChooserColumnOutputFloat(const FString& ChooserTablePath, const FString& BindingPropertyChain, int32 ContextIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeChooserLibrary::AddChooserColumnOutputFloat requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

int32 UUnrealBridgeChooserLibrary::AddChooserColumnOutputObject(const FString& ChooserTablePath, const FString& BindingPropertyChain, int32 ContextIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeChooserLibrary::AddChooserColumnOutputObject requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

bool UUnrealBridgeChooserLibrary::RemoveChooserColumn(const FString& ChooserTablePath, int32 ColumnIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeChooserLibrary::RemoveChooserColumn requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeChooserLibrary::SetChooserColumnDisabled(const FString& ChooserTablePath, int32 ColumnIndex, bool bDisabled)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeChooserLibrary::SetChooserColumnDisabled requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UUnrealBridgeChooserLibrary::SetChooserCellRaw(const FString& ChooserTablePath, int32 ColumnIndex, int32 RowIndex, const FString& T3DValue)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeChooserLibrary::SetChooserCellRaw requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FBridgeCHTEvaluation UUnrealBridgeChooserLibrary::EvaluateChooserWithContextObject(const FString& ChooserTablePath, const FString& ContextObjectPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeChooserLibrary::EvaluateChooserWithContextObject requires UE 5.7+ — call ignored on this engine version"));
	return FBridgeCHTEvaluation{};
}

TArray<FBridgeCHTRowResult> UUnrealBridgeChooserLibrary::EvaluateChooserMultiWithContextObject(const FString& ChooserTablePath, const FString& ContextObjectPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeChooserLibrary::EvaluateChooserMultiWithContextObject requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeCHTRowResult>{};
}

TArray<FBridgeCHTRowResult> UUnrealBridgeChooserLibrary::ListPossibleResults(const FString& ChooserTablePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UUnrealBridgeChooserLibrary::ListPossibleResults requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FBridgeCHTRowResult>{};
}

#endif // UE_VERSION_OLDER_THAN(5, 7, 0)
